### ISSUE TITLE
User page shows up as host error 

### ISSUE THREAD

**Issue by ThunderHen** [dragynfruit/pasted#2]
User pages show as host error https://pasted.drakeerv.com/u/dereksir https://pastebin.com/u/dereksir
Or 
https://pasted.drakeerv.com/u/volochai
Also wanted to say cool project thanks for makeing it.

**Comment by drakeerv** [comment]
I might know what is going on let me check and Ill hopefully have an update. Thanks!

**Comment by drakeerv** [comment]
Fixed it! Should be good in 1.2.11. I fixed it in the official instance.
